trigger:
- main


pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    ls
    npm install --cache /tmp/empty-cache
  displayName: 'npm install'
  workingDirectory: '$(Build.SourcesDirectory)/App'

- script: |
    npm run build
  displayName: 'npm build'
  workingDirectory: '$(Build.SourcesDirectory)/App'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/App'
    contents: |
       *
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: cv
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'

- task: DownloadPipelineArtifact@2
  inputs:
    source: 'current'
    artifactName: cv
    path: $(Build.ArtifactStagingDirectory)
    
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-mvp-subscription'
    appType: 'webAppLinux'
    appName: 'danidu-resume-cv-web'
    resourceGroupName: 'danidu-resume-cv-rg'
    package: '.'
