trigger:
- none

name: CV-Web-App

pool:
  vmImage: windows-latest

stages:
- stage: Deploy_CV_WEB
  
  jobs:
  - deployment: 'Lint_Web_App'
    displayName: 'Lint_Web_App'
    environment: Azure-IAC
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: CopyFiles@2
            inputs:
              contents: 'app/**'
              targetFolder: $(Build.ArtifactStagingDirectory)

          - script: |
              npm install
            displayName: 'npm install'

          - script: |
              npm run build
            displayName: 'npm build'

          # - task: CopyFiles@2
          #   inputs:
          #     sourceFolder: '$(Build.SourcesDirectory)'
          #     contents: |
          #       src/*
          #       dist/*
          #     targetFolder: '$(Build.ArtifactStagingDirectory)'
          #   displayName: 'Copy project files'

          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: e2e-server
              targetPath: '$(Build.ArtifactStagingDirectory)'
              publishLocation: 'pipeline'
            displayName: 'Publish npm artifact'

          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'azure-mvp-subscription'
          #     scriptType: ps
          #     scriptLocation: inlineScript
          #     inlineScript: |
          #       az --version
          #       Compress-Archive -Path $(Build.ArtifactStagingDirectory)/* -DestinationPath webApp.zip



          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'azure-mvp-subscription'
          #     scriptType: ps
          #     scriptLocation: inlineScript
          #     inlineScript: |
          #       az --version
          #       az deployment sub create -l 'australiaeast' `
          #       --template-file 'bicep/main/cv-webapp.main.bicep' `
          #       --parameters 'bicep/main/cv-webapp.main.bicepparam'

          # - task: DownloadPipelineArtifact@2
          #   inputs:
          #     source: 'current'
          #     path: $(Build.ArtifactStagingDirectory)

          # - task: AzureWebApp@1
          #   inputs:
          #     azureSubscription: 'azure-mvp-subscription'
          #     appType: 'webAppLinux'
          #     appName: 'danidu-resume-cv-web'
          #     resourceGroupName: 'danidu-resume-cv-rg'
          #     package: '$(System.DefaultWorkingDirectory)/webApp.zip'