trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: AzureCLI@2
    name: LintSubscriptionBuild
    displayName: 'Run preflight validation' 
    inputs: 
      azureSubscription: ${{ variables.azureServiceConnection }}
      scriptType: 'pscore'  
      scriptLocation: 'inlineScript'  
      inlineScript: |
        az account set --subscription 'SUBID'
        az deployment sub what-if --location ${{ variables.location }} `
        --template-file bicep/main/cv-webapp.main.bicep `
        --parameters bicep/main/cv-webapp.main.bicepparam


- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    ls
    npm install --cache /tmp/empty-cache
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: PublishPipelineArtifact@1
  inputs:
    artifactName: cv
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'

- task: DownloadPipelineArtifact@2
  inputs:
    source: 'current'
    artifactName: cv
    targetPath: $(Build.SourcesDirectory)
    
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-mvp-subscription'
    appType: 'webAppLinux'
    appName: 'danidu-resume-cv-web'
    resourceGroupName: 'danidu-resume-cv-rg'
    package: $(Build.SourcesDirectory)/**/*.zip
