trigger:
- main


pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    ls
    npm install --cache /tmp/empty-cache
  displayName: 'npm install'
  workingDirectory: '$(Build.SourcesDirectory)/App'

- script: |
    npm run build
  displayName: 'npm build'
  workingDirectory: '$(Build.SourcesDirectory)/App'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/App'
    contents: |
       *
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: cv
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'

- task: DownloadPipelineArtifact@2
  inputs:
    source: 'current'
    path: $(Build.ArtifactStagingDirectory)
    
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-mvp-subscription'
    appType: 'webAppLinux'
    appName: 'danidu-resume-cv-web'
    resourceGroupName: 'danidu-resume-cv-rg'
    package: '.'

# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'azure-mvp-subscription'
#     appType: 'webAppLinux'
#     WebAppName: 'danidu-resume-cv-web'
#     packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

# trigger:
# - none

# name: CV-Web-App

# pool:
#   vmImage: 'ubuntu-latest'

# stages:
# - stage: Deploy_CV_WEB
  
#   jobs:
#   - deployment: 'Lint_Web_App'
#     displayName: 'Lint_Web_App'
#     environment: Azure-IAC
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - checkout: self

#           - task: UseNode@1
#             inputs:
#               version: '16.x'
#             displayName: 'Install Node.js'
          
#           - task: CopyFiles@2
#             inputs:
#               contents: 'app/**'
#               targetFolder: $(Build.ArtifactStagingDirectory)
#           - script: |
#               npm install
#             displayName: 'npm install'
#             workingDirectory: '$(Build.ArtifactStagingDirectory)/app'

#           - script: |
#               npm run build
#             displayName: 'npm build'

         
#           # - task: CopyFiles@2
#           #   inputs:
#           #     sourceFolder: '$(Build.SourcesDirectory)'
#           #     contents: |
#           #       src/*
#           #       dist/*
#           #     targetFolder: '$(Build.ArtifactStagingDirectory)'
#           #   displayName: 'Copy project files'

#           - task: PublishPipelineArtifact@1
#             inputs:
#               artifactName: e2e-server
#               targetPath: '$(Build.ArtifactStagingDirectory)'
#               publishLocation: 'pipeline'
#             displayName: 'Publish npm artifact'

#           # - task: AzureCLI@2
#           #   inputs:
#           #     azureSubscription: 'azure-mvp-subscription'
#           #     scriptType: ps
#           #     scriptLocation: inlineScript
#           #     inlineScript: |
#           #       az --version
#           #       Compress-Archive -Path $(Build.ArtifactStagingDirectory)/* -DestinationPath webApp.zip



#           # - task: AzureCLI@2
#           #   inputs:
#           #     azureSubscription: 'azure-mvp-subscription'
#           #     scriptType: ps
#           #     scriptLocation: inlineScript
#           #     inlineScript: |
#           #       az --version
#           #       az deployment sub create -l 'australiaeast' `
#           #       --template-file 'bicep/main/cv-webapp.main.bicep' `
#           #       --parameters 'bicep/main/cv-webapp.main.bicepparam'

#           # - task: DownloadPipelineArtifact@2
#           #   inputs:
#           #     source: 'current'
#           #     path: $(Build.ArtifactStagingDirectory)

#           # - task: AzureWebApp@1
#           #   inputs:
#           #     azureSubscription: 'azure-mvp-subscription'
#           #     appType: 'webAppLinux'
#           #     appName: 'danidu-resume-cv-web'
#           #     resourceGroupName: 'danidu-resume-cv-rg'
#           #     package: '$(System.DefaultWorkingDirectory)/webApp.zip'